version: '3.7'
services: 
  nginx: 
    build: 
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: mayconm/nginx
    ports: 
      - "8080:80"
    networks: 
      - production-network
    depends_on: 
      - "python_api"
    links: 
      - "python_api"

  python_api:
    build:
      dockerfile: ./docker/Dockerfile
      context: .
    image: mayconmoreira/python
    expose: 
      - "5000"
    networks: 
      - production-network
    


networks: 
  production-network:
    driver: bridge